export const AESOP_PRINTED_TOC_TITLES = [
  "The Wolf and the Lamb",
  "The Fox and the Lion",
  "The Dog and his Shadow",
  "The Crab and his Mother",
  "The Fox and the Grapes",
  "The Wolf and the Crane",
  "The Ants and the Grasshoppers",
  "The Frogs who asked for a King",
  "The Donkey in the Lion’s Skin",
  "The Mice in Council",
  "The Kid and the Wolf",
  "The Hawk and the Nightingale",
  "The Crow and the Pitcher",
  "The Ant and the Dove",
  "The Ox and the Frog",
  "The Bat and the Weasels",
  "The Fox and the Goat",
  "The Woman and her Hen",
  "The Dog in the Manger",
  "The Mouse, the Frog, and the Hawk",
  "The Shepherd’s Boy and the Wolf",
  "The Fisherman and the Little Fish",
  "The Fox and the Crow",
  "The Partridge and the Fowler",
  "The Thirsty Pigeon",
  "The Three Tradesmen",
  "The Hares and the Frogs",
  "The Eagle and the Arrow",
  "The Eagle and the Fox",
  "The Drum and the Vase of Sweet Herbs",
  "The Two Frogs",
  "The Lion and the Mouse",
  "The Mouse, the Cat, and the Cock",
  "The Ax and the Trees",
  "The Jackdaw and the Sheep",
  "The Cat and the Cock",
  "The Wolf and the Goat",
  "The Hen and the Swallow",
  "Stone Broth",
  "The Mule and the Grasshoppers",
  "The Gnat and the Bull",
  "A Fox and a Crab",
  "The Donkey and the Frogs",
  "The Nurse and the Wolf",
  "The Cat and the Martins",
  "The Cock and the Fox",
  "The Horse and his Rider",
  "The Fox and the Stork",
  "The Dog, the Cock, and the Fox",
  "The Fly and the Moth",
  "The Boy Bathing",
  "The Hare and the Tortoise",
  "The Arab and his Camel",
  "The Fox who had lost his Tail",
  "The Boys and the Frogs",
  "The Swallow and the Other Birds",
  "The Farmer and the Snake",
  "The Raven and the Swan",
  "The Birds, the Beasts, and the Bat",
  "The Man, his Son, and his Donkey",
  "The Country Mouse and the City Mouse",
  "The Cock and the Jewel",
  "The Old Hound",
  "The Vain Jackdaw",
  "The Donkey and the Lap Dog",
  "The One-Eyed Doe",
  "The Camel",
  "The Wolf and the House Dog",
  "The Oak and the Reed",
  "The Dog and the Hare",
  "The Hawk, Kite, and Pigeons",
  "The War Horse and the Mule",
  "The Wind and the Sun",
  "The Bear and the Two Travelers",
  "The Two Goats",
  "The Bull and the Calf",
  "The Fawn and his Mother",
  "The Mule and his Shadow",
  "The Blind Man and the Lame Man",
  "The Two Pots",
  "The Quack Frog",
  "The Wolf in Sheep’s Clothing",
  "The Boy and the Filberts",
  "The Miser",
  "The Widow and her Little Maids",
  "The Charcoal Burner and the Fuller",
  "The Porcupine and the Snakes",
  "The Bundle of Sticks",
  "The Mischievous Dog",
  "The Dog and the Oyster",
  "The Fox and the Leopard",
  "The Dogs and the Hides",
  "The Woodman and the Trees",
  "The Milkmaid and her Pail of Milk",
  "The Cat and the Fox",
  "The Monkey and the Cat",
  "The Wolf and the Shepherd",
  "The Wolf, the Fox, and the Ape",
  "The Blind Man and the Whelp",
  "The Spendthrift and the Swallow",
  "The Boar and the Fox",
  "Hercules and the Wagoner",
  "The Mules and the Robbers",
  "The Swallow and the Crow",
  "Jupiter and the Bee",
  "The Two Travelers",
  "The Kid and the Wolf",
  "The Gourd and the Pine",
  "The Hare and the Hound",
  "The Owl and the Grasshopper",
  "The Mule eating Thistles",
  "The Sick Stag",
  "The Wolf and the Shepherds",
  "The Boy and the Nettle",
  "The Hares and the Foxes",
  "Mercury and the Woodman",
  "The Rat and the Elephant",
  "The Husbandman and the Stork",
  "The Satyr and the Traveler",
  "The Stag at the Lake",
  "The Peasant and the Apple Tree",
  "Jupiter, Neptune, Minerva, and Momus",
  "The Farthing Rushlight",
  "The Horse and the Groom",
  "The Trumpeter taken Prisoner",
  "The Boasting Traveler",
  "The Hedge and the Vineyard",
  "The Mouse and the Weasel",
  "The Wolf and the Sheep",
  "A Widow and her Sheep",
  "The Man and the Lion",
  "The Lioness",
  "The Boy who stole Apples",
  "The Goose with the Golden Eggs",
  "The Old Man and Death",
  "A Father and his Two Daughters",
  "The Sick Lion and the Fox",
  "The Mountain in Labor",
  "Jupiter and the Camel",
  "The Moon and her Mother",
  "The Horse and the Stag",
  "The Council held by the Rats",
  "The Rain Cloud",
  "The Elephant in Favor",
  "The Cuckoo and the Eagle",
  "The Fox in the Ice",
  "The Inquisitive Man",
  "The Squirrel in Service",
  "The Wolf and the Cat"
]

// Printed APPENDIX mini-index (source PDF pages 13-14): 28 shorter classroom
// reprints of primary fables (same titles, different prose). "Note" on p215 is
// front matter for the appendix, not a fable title.
export const AESOP_APPENDIX_TOC_TITLES = [
  "The Wolf and the Lamb",
  "The Fox and the Lion",
  "The Dog and his Shadow",
  "The Crab and his Mother",
  "The Fox and the Grapes",
  "The Wolf and the Crane",
  "The Ants and the Grasshoppers",
  "The Frogs who asked for a King",
  "The Donkey in the Lion's Skin",
  "The Mice in Council",
  "The Kid and the Wolf",
  "The Hawk and the Nightingale",
  "The Crow and the Pitcher",
  "The Ant and the Dove",
  "The Ox and the Frog",
  "The Bat and the Weasels",
  "The Fox and the Goat",
  "The Woman and her Hen",
  "The Dog in the Manger",
  "The Mouse, the Frog, and the Hawk",
  "The Shepherd Boy and the Wolf",
  "The Fisherman and the Little Fish",
  "The Fox and the Crow",
  "The Partridge and the Fowler",
  "The Thirsty Pigeon",
  "The Three Tradesmen",
  "The Hares and the Frogs",
  "The Eagle and the Fox",
]

export const AESOP_PRIMARY_TOC_ENTRY_COUNT = AESOP_PRINTED_TOC_TITLES.length
export const AESOP_APPENDIX_TOC_ENTRY_COUNT = AESOP_APPENDIX_TOC_TITLES.length
// Primary TOC lists "The Kid and the Wolf" twice (printed pp. 23 and 161).
export const AESOP_PRIMARY_TOC_UNIQUE_KEY_COUNT = 148
export const AESOP_EXPECTED_STORY_OPENING_COUNT =
  AESOP_PRIMARY_TOC_ENTRY_COUNT + AESOP_APPENDIX_TOC_ENTRY_COUNT
