export const MAYA_PRINTED_TOC_POEMS = [
  "They Went Home",
  "The Gamut",
  "A Zono Man",
  "To a Man",
  "Late October",
  "No Loser, No Weeper",
  "When You Come to Me",
  "Remembering",
  "In a Time",
  "Tears",
  "The Detached",
  "To a Husband",
  "Accident",
  "Let's Majeste",
  "After",
  "The Mothering Blackness",
  "On Diverse Deviations",
  "Mourning Grace",
  "How I Can Lie to You",
  "Sounds Like Pearls",
  "When I Think About Myself",
  "On a Bright Day, Next Week",
  "Letter to. an Aspiring Junkie",
  "Miss Scarlett, Mr. Rhett and Other Latter-Day Saints",
  "Times-Square-Shoeshine-Composition",
  "Faces",
  "To a Freedom Fighter",
  "Riot: 60's",
  "We Saw Beyond Our Seeming",
  "Black Ode",
  "No No No No",
  "My Guilt",
  "The Calling of Names",
  "On Working White Liberals",
  "Sepia Fashion Show",
  "The Thirteens (Black)",
  "The Thirteens (White)",
  "Harlem Hopscotch",
  "Pickin Em Up and Layin Em Down",
  "Here s to Adhering",
  "On Reaching Forty",
  "The Telephone",
  "Passing Time",
  "Now Long Ago",
  "Greyday",
  "Poor Girl",
  "Come. And Be My Baby",
  "Senses of Insecurity",
  "Alone",
  "Communication I",
  "Communication II",
  "Wonder",
  "A Conceit",
  "Request",
  "Africa",
  "America",
  "For Us, Who Dare Not Dare",
  "Lord, in My Heart",
  "Artful Pose",
  "The Couple",
  "The Pusher",
  "Chicken-Licken",
  "I Almost Remember",
  "Prisoner",
  "Woman Me",
  "JohnJ.",
  "Southeast Arkanasia",
  "Song for the Old Ones",
  "Child Dead in Old Seas",
  "Take Time Out",
  "Elegy",
  "Reverses",
  "Little Girl Speakings",
  "This Winter Day",
  "A Kind of Love, Some Say",
  "Country Lover",
  "Remembrance",
  "Where We Belong, A Duet",
  "Phenomenal Woman",
  "Men",
  "Refusal",
  "Just for a Time",
  "Junkie Monkey Reel",
  "The Lesson",
  "California Prodigal",
  "My Arkansas",
  "Through the Inner City to the Suburbs",
  "Lady Luncheon Club",
  "Momma Welfare Roll",
  "The Singer Will Not Sing",
  "Willie",
  "To Beat the Child Was Bad Enough",
  "Woman Work",
  "One More Round",
  "The Traveler",
  "Kin",
  "The Memory",
  "Still I Rise",
  "Ain't That Bad?",
  "Life Doesn't Frighten Me",
  "Bump d'Bump",
  "On Aging",
  "In Retrospect",
  "Just Like Job",
  "Call Letters: Mrs. V. B.",
  "Thank You, Lord",
  "Awaking in New York",
  "A Good Woman Feeling Bad",
  "The Health-Food Diner",
  "A Georgia Song",
  "Unmeasured Tempo",
  "Amoebaeanfor Daddy",
  "Recovery",
  "Impeccable Conception",
  "Caged Bird",
  "Avec Merciy Mother",
  "Arrival",
  "A Plagued Journey",
  "Starvation",
  "Contemporary Announcement",
  "Prelude to a Parting",
  "Martial Choreograph",
  "To a Suitor",
  "Insomniac",
  "Weekend Glory",
  "The Lie",
  "Prescience",
  "Family Affairs",
  "Changes",
  "Brief Innocence",
  "The Last Decision",
  "Slave Coffle",
  "My Life Has Turned to Blue",
  "Worker's Song",
  "Human Family",
  "Man Bigot",
  "Old Folks Laugh",
  "Is Love",
  "Forgive",
  "Insignificant",
  "Love Letter",
  "Equality",
  "Coleridge Jackson",
  "Why Are They Happy People?",
  "Son to Mother",
  "Known to Eve and Me",
  "These Yet to Be United States",
  "Me and My Work",
  "Changing",
  "Born That Way",
  "Televised",
  "Nothing Much",
  "Glory Falls",
  "London",
  "Savior",
  "Many ama More",
  "The New House",
  "Our Grandmothers",
  "Preacher, Doni Send Me",
  "Fightin'Was Natural",
  "Loss of Love",
  "Seven Women's Blessed Assurance",
  "In My Missouri",
  "They Ask Why",
  "When Great Trees Fall",
  "On the Pulse of Morning"
]

// Printed Contents vs body-title OCR drift confirmed by raw pdfjs (same poem,
// different spelling in the Contents page extraction vs promoted body heading).
export const MAYA_CONTENTS_TO_BODY_TITLE_ALIASES = [
  ["A Zono Man", "A Zorro Man"],
  ["Many ama More", "Many and More"],
  ["Here s to Adhering", "Here's to Adhering"],
  ["JohnJ.", "John J"],
  ["Amoebaeanfor Daddy", "Amoebaean for Daddy"],
  ["Slave Coffle", "Slave Cqffle"],
  ["Preacher, Doni Send Me", "Preacher, Don't Send Me"],
  ["Fightin'Was Natural", "Fightin' Was Natural"],
]
